[versions]
serenity = "0.1.0-SNAPSHOT"

[libraries]
annotations = { module = "net.derfruhling.serenity:serenity-annotations", version.ref = "serenity" }
core = { module = "net.derfruhling.serenity:serenity-core", version.ref = "serenity" }
server-ktor = { module = "net.derfruhling.serenity:serenity-ktor-server", version.ref = "serenity" }
component-inlineStyle = { module = "net.derfruhling.serenity:serenity-inline-style", version.ref = "serenity" }
component-localization = { module = "net.derfruhling.serenity:serenity-localization", version.ref = "serenity" }
test = { module = "net.derfruhling.serenity:serenity-test", version.ref = "serenity" }

[plugins]
base = { id = "net.derfruhling.serenity.base", version.ref = "serenity" }
compilerPlugin = { id = "net.derfruhling.serenity.compiler-plugin", version.ref = "serenity" }
server = { id = "net.derfruhling.serenity.server", version.ref = "serenity" }
web = { id = "net.derfruhling.serenity.web", version.ref = "serenity" }
conventions = { id = "net.derfruhling.serenity.convention", version.ref = "serenity" }
resources = { id = "net.derfruhling.serenity.resources", version.ref = "serenity" }
all = { id = "net.derfruhling.serenity", version.ref = "serenity" }
stylist-sass = { id = "net.derfruhling.serenity.stylist-sass", version.ref = "serenity" }
