package net.derfruhling.serenity

import androidx.compose.runtime.DisallowComposableCalls
import net.derfruhling.serenity.annotations.Intrinsic
import net.derfruhling.serenity.annotations.PageContractsDsl
import net.derfruhling.serenity.annotations.PageExtensionImplementationApi
import net.derfruhling.serenity.annotations.PromotedLambda
import net.derfruhling.serenity.modularity.extension.AbstractPageExtension
import net.derfruhling.serenity.modularity.extension.AbstractPageExtensionVoid
import kotlin.contracts.ExperimentalContracts
import kotlin.contracts.InvocationKind
import kotlin.contracts.contract
import kotlin.reflect.KClass

@PageContractsDsl
interface PageContract {
    var title: String?

    @PageExtensionImplementationApi
    fun <T : AbstractPageExtension<*>> extend(kClass: KClass<T>, value: T)
}

inline fun <reified T : AbstractPageExtensionVoid> PageContract.extend(value: T) {
    @OptIn(PageExtensionImplementationApi::class)
    extend(T::class, value)
}

inline fun <reified T : AbstractPageExtension<C>, C> PageContract.extend(
    value: T,
    noinline cfg: C.() -> Unit
) {
    @OptIn(PageExtensionImplementationApi::class)
    extend(T::class, value.also { it.configure(this, cfg) })
}

inline fun <reified T : AbstractPageExtensionVoid> PageContract.extend(value: () -> T) {
    @OptIn(PageExtensionImplementationApi::class)
    extend(T::class, value())
}

inline fun <reified T : AbstractPageExtension<C>, C> PageContract.extend(
    value: () -> T,
    noinline cfg: C.() -> Unit
) {
    @OptIn(PageExtensionImplementationApi::class)
    extend(T::class, value().also { it.configure(this, cfg) })
}

/**
 * This function can be used to define additional metadata for pages in code.
 * The lambda you pass here will be "pulled" out from the function and called
 * before your [@Page][net.derfruhling.serenity.annotations.Page] function ever
 * runs. Despite this, you can still use parameters, **but you cannot use other
 * local variables!**
 *
 * The local function generated by the compiler when you call this function
 * will get moved into the resulting [PageHolder] class, with all parameter
 * references replaced with property getter calls as appropriate.
 * To denote this behavior, the lambda type has been annotation with
 * [@PromotedLambda][PromotedLambda].
 *
 * As such, if you call this function, it should be the first thing called
 * in the whole [@Page][net.derfruhling.serenity.annotations.Page].
 */
@OptIn(ExperimentalContracts::class)
@Intrinsic
fun pageContract(fn: ContractFun) {
    @Suppress("WRONG_INVOCATION_KIND")
    contract {
        callsInPlace(fn, kind = InvocationKind.EXACTLY_ONCE)
    }

    throw NotImplementedError()
}

typealias ContractFun = @PromotedLambda @DisallowComposableCalls PageContract.() -> Unit
